admins: []
forwards:
- source: -1001380765184
  dest:
  - -1001583330090
  offset: 2900
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2.0
plugins: {}
