admins: []
forwards:
- source: -1001772348499
  dest:
  - -1001515802491
  offset: 5542
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.5
plugins: {}
