admins: []
forwards:
- source: -1001600836554
  dest:
  - -1001515802491
  offset: 500
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins: {}
