admins: []
forwards:
- source: -1001669421873
  dest:
  - -1001511215621
  offset: 436
  end: 435
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.5
plugins: {}
