admins: []
forwards:
- source: -1001772762311
  dest:
  - -1001511215621
  offset: 3688
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.5
plugins: {}
