admins: []
forwards:
- source: -1001757507535
  dest:
  - -1001511215621
  offset: 1036
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.5
plugins: {}
