admins: []
forwards:
- source: -1001512595228
  dest:
  - -1001546147967
  offset: 1335
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2.0
plugins: {}
