admins: []
forwards:
- source: t.me/khansirptnaaaaa
  dest:
  - -1001750586619
  offset: 1649
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 4.0
plugins: {}
