admins: []
forwards:
- source: -1001542157449
  dest:
  - -1001583330090
  offset: 24097
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.0
plugins: {}
