admins: []
forwards:
- source: -1001511215621
  dest:
  - -1001760262813
  offset: 36031
  end: 36030
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins: {}
