admins: []
forwards:
- source: -1001791053058
  dest:
  - -1001511215621
  offset: 12599
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.0
plugins: {}
