admins: []
forwards:
- source: -1001569665792
  dest:
  - -1001675068301
  offset: 1177
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.5
plugins: {}
