admins: []
forwards:
- source: -1001716769907
  dest:
  - -1001515802491
  offset: 218
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.5
plugins: {}
