admins: []
forwards:
- source: -1001758794061
  dest:
  - -1001511215621
  offset: 596
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2.0
plugins: {}
