admins: []
forwards:
- source: -1001684118622
  dest:
  - -1001750586619
  offset: 2789
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2.0
plugins: {}
