admins: []
forwards:
- source: -1001750743367
  dest:
  - -1001750586619
  offset: 2297
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins: {}
