admins: []
forwards:
- source: -1001717319730
  dest:
  - -1001642906725
  offset: 1027
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins: {}
