admins: []
forwards:
- source: -1001511215621
  dest:
  - -1001649884289
  offset: 22746
  end: 23705
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.0
plugins: {}
