admins: []
forwards:
- source: -1001709414793
  dest:
  - -1001584058081
  offset: 1424
  end: 1422
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2.0
plugins: {}
