admins: []
forwards:
- source: -1001622786341
  dest:
  - -1001750586619
  offset: 4403
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 5.0
plugins: {}
