admins: []
forwards:
- source: -1001503055418
  dest:
  - -1001724431484
  offset: 666
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2.0
plugins: {}
