admins: []
forwards:
- source: -1001508927519
  dest:
  - -1001642906725
  offset: 4609
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2.0
plugins: {}
