admins: []
forwards:
- source: -1001699398614
  dest:
  - -1001584058081
  offset: 4883
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2.0
plugins: {}
