admins: []
forwards:
- source: -1001675557443
  dest:
  - -1001515802491
  offset: 41402
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.2
plugins: {}
