admins: []
forwards:
- source: -721216538
  dest:
  - -1001760176210
  offset: 30004
  end: 29992
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2.0
plugins: {}
