admins: []
forwards:
- source: -1001170613264
  dest:
  - -1001583330090
  offset: 1082
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.5
plugins: {}
