admins: []
forwards:
- source: -100721216538
  dest:
  - -1001760176210
  offset: 0
  end: 3388
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 2.0
plugins: {}
